### ISSUE TITLE
aspect ratio

### ISSUE THREAD

**Issue by AMBIENTE1** [jonlund/SoftKeyboardView#1]
Hello jonlund, thanks for your project, nice work for me!

I try add button "." in case for .numberPad [.blank,.done,"0",.backspace,**"."**] and the aspect ratio is wrong.
Can you please help me?

<img width="723" alt="Snímek obrazovky 2023-07-24 v 6 52 01" src="https://github.com/jonlund/SoftKeyboardView/assets/40637037/b9bfb1e1-4a1e-4c93-b255-015f20078f4c">

**Comment by jonlund** [comment]
I just made an update that adds the "." for decimal type. It should fix your problem.
<img width="1045" alt="Screenshot 2023-07-24 at 12 18 11 PM" src="https://github.com/jonlund/SoftKeyboardView/assets/7719934/b0b83449-b5b9-4eaf-b324-f954f5c75002">

**Comment by AMBIENTE1** [comment]
Thanks a lot!
